/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kidfolk_androidRDP_AndroidRDPActivity */

#ifndef _Included_org_kidfolk_androidRDP_AndroidRDPActivity
#define _Included_org_kidfolk_androidRDP_AndroidRDPActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    getenv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_getenv
  (JNIEnv *, jobject);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    setUsername
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_setUsername
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    setPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_setPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    rdp_connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_rdp_1connect
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    rdpdr_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_rdpdr_1init
  (JNIEnv *, jobject);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    rdp_main_loop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_rdp_1main_1loop
  (JNIEnv *, jobject);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    rdp_disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_rdp_1disconnect
  (JNIEnv *, jobject);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    rdp_reset_state
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_rdp_1reset_1state
  (JNIEnv *, jobject);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    cache_save_state
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_cache_1save_1state
  (JNIEnv *, jobject);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    renderBitmap
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_renderBitmap
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
