/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kidfolk_androidRDP_RemoteView */

#ifndef _Included_org_kidfolk_androidRDP_RemoteView
#define _Included_org_kidfolk_androidRDP_RemoteView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kidfolk_androidRDP_RemoteView
 * Method:    native_handle_mouse_button
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_RemoteView_native_1handle_1mouse_1button
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
